export enum SuiteErrorCode {
  FORMAT_ERROR = 101,
  LOGIC_ERROR = 102,
  EXPIRED_KEYPAIR = 103,
  KEY_NOT_FOUND = 104,
  ENCODING_ERROR = 110,
  DECODING_ERROR = 111,
  FINGERPRINT_VERIFICATION_FAILURE = 129,
}
